### ISSUE TITLE
Default commands of live-preview.nvim

### ISSUE THREAD

**Issue by brianhuster** [brianhuster/live-preview.nvim#207]
For a long time, the default commands for [live-preview.nvim](https://github.com/brianhuster/live-preview.nvim) have been `:LivePreview` and `:StopPreview`. Now, I realize that is bad way to define user commands, I think user commands of the same plugin should use the same prefix, for example `:LiveStart` and `:LiveStop`. Or we can use a space between prefix and subcommand, like `:LivePreview start` and `:LivePreview stop`? I would like to know everyone's opinions

**Comment by Muizzyranking** [comment]
I think LivePreview start | stop is a better.

**Comment by brianhuster** [comment]
Why do you think so?

**Comment by Muizzyranking** [comment]
I think so because it is much easier to remember. I know I am using livepreview, I can just enter this and then use tab to check sub commands. It would also be easier to add more commands in the future.

**Comment by brianhuster** [comment]
With the release of v0.8, here are the default commands to work with live-preview.nvim
*  `LivePreview start` : equivalent to `LivePreview` in v0.7 and older
*  `LivePreview close` : equivalent to `StopPreview` in v0.7 and older 
*  `LivePreview pick` : similar to `Telescope livepreview` in v0.7 but also support `fzf-lua` and `mini.pick`
*  `LivePreview help` : for showing documents about these commands

Users can customize the main command (default to `LivePreview`) by changing the variable `opts.cmd` in config.
