### ISSUE TITLE
bug: files with spaces do not work

### ISSUE THREAD

**Issue by ravatex** [brianhuster/live-preview.nvim#254]
### Did you read the documentation and check existing issues?

- [X] I have read all the documentations ([README](https://github.com/brianhuster/live-preview.nvim), [`:h livepreview`](https://github.com/brianhuster/live-preview.nvim/blob/main/doc/livepreview.txt), [Wiki](https://github.com/brianhuster/live-preview.nvim/wiki))
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the [existing issues](https://github.com/brianhuster/live-preview.nvim/issues) and [closed issues](https://github.com/brianhuster/live-preview.nvim/issues?q=is%3Aissue+is%3Aclosed) issues

### Neovim version (nvim -v)

0.10.2

### Operating system/version

EndeavourOS Linux 2024.06.25

### Browser/version

Firefox

### Describe the bug

Whenever you try to open a LivePreview of a document that has any spaces in the name (or the path from the instance of neovim includes any whitespace) the preview is not available at the "correct" link. 

### Steps To Reproduce

`nvim "hello world.html"`
Paste or write any html (or markdown ect.)
e.g. 
```html
<!DOCTYPE html>
<html>
<body>

<h1> Hello </h1>

<p> World </p>

</body>
</html>
```

`:LivePreview start`

This will result in a 404 Not found error.

The link for this specific example will be: `http://localhost:5500/hello%20world.html`

### Expected Behavior

It is expected that the live preview will work regardless of the file path. However this issue may need to be marked as a feature instead of a bug, since it is not entirely obvious what the link should be.
 

### Health

```help
==============================================================================
livepreview: require("livepreview.health").check()

Check dependencies ~
- OK Nvim 0.10.2 is compatible with Live Preview
- OK `sh` is available
- OK `telescope` is installed
- OK `fzf-lua` is installed
- OK `mini.pick` is installed

Checkhealth server and process ~
- OK This Nvim process's PID is 4712
- OK Server is healthy on port 5500
- OK Server root: /home/ravatex/hello world

Check your live-preview.nvim config ~
- {
    autokill = false,
    browser = "default",
    cmd = "LivePreview",
    dynamic_root = false,
    port = 5500,
    sync_scroll = false
  }
```

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {{
        "brianhuster/live-preview.nvim",
        config = function()
            require("live-preview").setup({
            })
        end,
    }},
})
```

**Comment by brianhuster** [comment]
Fixed by [#255]
