### ISSUE TITLE
Press ENTER or type command to continue.

### ISSUE THREAD

**Issue by hsanson** [brianhuster/live-preview.nvim#28]
Nice plugin but whenever the plugin updates the preview I get 1000+1 `Press ENTER or type command to continue` prompts:

![image](https://github.com/user-attachments/assets/e184ef6a-0943-414e-acfc-df8d165dc689)

In the prompt area I can see the whole HTTP request/response communication and I have to press ENTER several times to make it dissapear. But then it appears again when saving or calling LivePreview.

**Comment by hsanson** [comment]
Removing all the `print` statements in `server.lua` file seems to solve the issue for me.

**Comment by brianhuster** [comment]
Fixed this. Please update the plugin

**Comment by hsanson** [comment]
Fix works, thanks.
