### ISSUE TITLE
Allow configuration to include custom CSS file(s)

### ISSUE THREAD

**Issue by alienman5k** [brianhuster/live-preview.nvim#49]
It would be really helpful to allow custom CSS to be included from the configuration file to change the appearance of the previewer. Maybe a section for MarkDown and a section for AsciiDoc

**Comment by brianhuster** [comment]
With the latest update, you can now embed html in markdown, which allow you to use external js and css files, as long as they are in `server root` (run `:chechhealth livepreview` to see path to server root, by default it is `:pwd`).

I know it is not exactly what you want, but I hope that give you a workaround way.
