### ISSUE TITLE
Image support?

### ISSUE THREAD

**Issue by Fizzify** [brianhuster/live-preview.nvim#86]
![image](https://github.com/user-attachments/assets/baccbfbc-1721-49c0-9bd9-57e20eef5216)

![image](https://github.com/user-attachments/assets/38536182-861b-4e99-a51b-a75d0156cb67)

**Comment by brianhuster** [comment]
This plugin does support image, from both local and the web, but the local one must be in the same directory as your markdown file or in one of its subdirectory. 

In that case, please make sure to provide relative path to the image, not absolute path
